export const environment = {
  production: true,
  RecipePageSize: 5,
  ShoppingListPageSize: 14,
  AdminUserListPageSize: 11,
  MediaListPageSize: 12,
  ApiKey: 'AIzaSyB3Jr8tp5wotjeS-re9iBSgX2b1zbM0Fx4',
  ConfirmEmailUrl: '/api/ConfirmEmail',
  ResendEmailUrl: '/api/ConfirmEmail/Send',
  ResetPasswordUrl: '/api/PasswordReset',
  SendEmailResetPassUrl: '/api/PasswordReset/Send',
  SignUpUrl: '/api/Accounts/SignUp',
  SignInUrl: '/api/Accounts/SignIn',
  GetSetRecipesUrl: '/api/Recipes',
  UploadFileUrl: '/api/Files',
  SearchRecipesUrl: '/api/Recipes/Search',
  GetSetShoppingListUrl: '/api/ShoppingList',
  GetSetUsersUrl: '/api/Users',
};
